apiVersion: v2
name: prometheus-monitoring
version: 1.0.0
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: prometheus
    version: 25.1.0
    repository: https://prometheus-community.github.io/helm-charts
