apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: experiments
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: experiments
spec:
  project: iris-tech
  source:
    repoURL: https://github.com/Jindra-Dev04/k8s-testing.git
    targetRevision: HEAD
    path: experiments/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
