apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`grafana.nextap.codes`)
    priority: 10
    services:
    - name: grafana
      port: 80