mimir-distributed:
  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            endpoint: fra1.digitaloceanspaces.com
            region: us-east-1
            secret_access_key: "${AWS_SECRET_ACCESS_KEY}" 
            access_key_id: "${AWS_ACCESS_KEY_ID}" 

      blocks_storage:
        s3:
          bucket_name: mimir-nextap
      alertmanager_storage:
        s3:
          bucket_name: mimir-alertmanager
      ruler_storage:
        s3:
          bucket_name: mimir-ruler

  runtimeConfig:
    ingester_limits:
      max_ingestion_rate: 2000000
      max_series: 150000000
      max_tenants: 1000
      max_inflight_push_requests: 300000

  global:
    extraEnvFrom:
    - secretRef:
        name: mimir-secrets
  
  minio:
    enabled: false
  
  gateway:
    enabledNonEnterprise: true

  metaMonitoring:
    grafanaAgent:
      enabled: false
      metrics:
        remote:
          url: http://mimir-gateway.mimir.svc.cluster.local/api/v1/push
        scrapeK8s:
          enabled: false
          

    dashboards:
      enabled: true

    serviceMonitor:
      enabled: true

    prometheusRule:
      enabled: true
      mimirAlerts: false
      mimirRules: true
