mimir-distributed:
  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            endpoint: fra1.digitaloceanspaces.com
            region: us-east
            secret_access_key: "${AWS_SECRET_ACCESS_KEY}" 
            access_key_id: "${AWS_ACCESS_KEY_ID}" 

      blocks_storage:
        s3:
          bucket_name: mimir-nextap
      alertmanager_storage:
        s3:
          bucket_name: mimir-alertmanager
      ruler_storage:
        s3:
          bucket_name: mimir-ruler
  global:
    extraEnvFrom:
    - secretRef:
        name: mimir-secrets
  
  minio:
    enabled: false