mimir-distributed:
  mimir:
    structuredConfig:
      limits:
        max_global_series_per_user: 10000000
      common:
        storage:
          backend: s3
          s3:
            endpoint: fra1.digitaloceanspaces.com
            region: us-east-1
            secret_access_key: "${AWS_SECRET_ACCESS_KEY}" 
            access_key_id: "${AWS_ACCESS_KEY_ID}" 

      blocks_storage:
        s3:
          bucket_name: mimir-nextap
      alertmanager_storage:
        s3:
          bucket_name: mimir-alertmanager
      ruler_storage:
        s3:
          bucket_name: mimir-ruler

  runtimeConfig:
    ingester_limits:
      max_ingestion_rate: 2000000
      max_series: 150000000
      max_tenants: 1000
      max_inflight_push_requests: 300000
    distributor_limits: # limits that each distributor replica enforces
      max_ingestion_rate: 2000000
      max_inflight_push_requests: 300000
      max_inflight_push_requests_bytes: 50000000
    overrides:
      tenant1:
        ingestion_rate: 5000000
        ingestion_burst_size: 5000000

  global:
    extraEnvFrom:
    - secretRef:
        name: mimir-secrets
  
  minio:
    enabled: false
  
  gateway:
    enabledNonEnterprise: true

  metaMonitoring:
    grafanaAgent:
      enabled: false
      metrics:
        remote:
          url: http://prometheus-kube-prometheus-prometheus.prometheus:9090/
        scrapeK8s:
          enabled: false
          

    dashboards:
      enabled: true

    serviceMonitor:
      enabled: true

    prometheusRule:
      enabled: true
      mimirAlerts: false
      mimirRules: true

  distributor:
    replicas: 8
    resources:
      limits:
        memory: 5.7Gi
      requests:
        cpu: 1
        memory: 2Gi
    extraArgs:
      distributor.ingestion-rate-limit: "10000000000000"

  ingester:
    replicas: 8
    resources:
      limits:
        memory: 12Gi
      requests:
        cpu: 1
        memory: 2Gi
    extraArgs:
      ingester.max-global-series-per-user: "0"
      ingester.max-global-series-per-metric: "0"
    zoneAwareReplication:
      enabled: false

  store_gateway:
    replicas: 3
    zoneAwareReplication:
      enabled: false

  querier:
    extraArgs:
      querier.max-fetched-chunks-per-query: "8000000"
